name: sync_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  ######### UI
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.3
  flutter_slidable: ^3.1.0 # Check for the latest version on pub.dev
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1
  url_launcher: ^6.0.20
  another_flushbar: ^1.12.30
  ###core
  get_storage: ^2.1.1
  get: 4.6.6
  flutter_screenutil: ^5.9.1
  go_router: ^12.1.1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5


  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  dartz: ^0.10.1
  get_it: ^7.7.0
  logger: ^2.3.0
  lottie: ^3.1.2
  flutter_switch: ^0.3.2
  dotted_border: ^2.1.0
  mime: ^1.0.5
  qr_flutter: ^4.1.0
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.1
  file_picker: ^8.0.5
  


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Medium.ttf
    
